# -*- coding: utf-8 -*-
"""fish image classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y2Aw2AF1e9T-u5tecIz-GvwzX-leS8bH
"""

!pip install icrawler -q

import os
import shutil
import random
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from PIL import Image

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from torchvision import datasets, transforms, models
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

from icrawler.builtin import BingImageCrawler
from icrawler.builtin import GoogleImageCrawler

import warnings
warnings.filterwarnings("ignore")

from google.colab import files
files.upload()  # upload kaggle.json here

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

# Download the dataset
!kaggle datasets download -d crowww/a-large-scale-fish-dataset -p fish_dataset --unzip

print("✅ Dataset downloaded!")

import os
for root, dirs, files in os.walk("fish_dataset"):
    level = root.replace("fish_dataset", "").count(os.sep)
    indent = " " * 2 * level
    print(f"{indent}{os.path.basename(root)}/")
    if level == 2:
        print(f"{indent}  → {len(files)} files")

import shutil
from pathlib import Path

DATA_DIR = Path("fish_dataset")

# Use the NA_Fish_Dataset which has clean images
SOURCE_DIR = DATA_DIR / "NA_Fish_Dataset"

# These are the actual classes available
CLASS_NAMES = [
    "Red Mullet", "Horse Mackerel", "Sea Bass",
    "Striped Red Mullet", "Shrimp", "Trout",
    "Black Sea Sprat", "Gilt Head Bream", "Red Sea Bream"
]

# Create train/val folders
for split in ["train", "val"]:
    for cls in CLASS_NAMES:
        (DATA_DIR / split / cls).mkdir(parents=True, exist_ok=True)

# Split 80/20
import random
print("🗂️ Splitting dataset...")
for cls in CLASS_NAMES:
    images = list((SOURCE_DIR / cls).glob("*.*"))
    images = [i for i in images if i.suffix.lower() in [".jpg", ".jpeg", ".png"]]
    random.shuffle(images)
    split_idx  = int(len(images) * 0.8)
    train_imgs = images[:split_idx]
    val_imgs   = images[split_idx:]
    for img in train_imgs:
        shutil.copy(img, DATA_DIR / "train" / cls / img.name)
    for img in val_imgs:
        shutil.copy(img, DATA_DIR / "val" / cls / img.name)
    print(f"  {cls:20s}: {len(train_imgs)} train | {len(val_imgs)} val")

print("\n✅ Dataset ready!")

import shutil, random
from pathlib import Path

DATA_DIR   = Path("fish_dataset")
SOURCE_DIR = DATA_DIR / "Fish_Dataset" / "Fish_Dataset"

CLASS_NAMES = [
    "Red Mullet", "Hourse Mackerel", "Sea Bass",
    "Striped Red Mullet", "Shrimp", "Trout",
    "Black Sea Sprat", "Gilt-Head Bream", "Red Sea Bream"
]

# Clear old train/val
import shutil
for split in ["train", "val"]:
    if (DATA_DIR / split).exists():
        shutil.rmtree(DATA_DIR / split)

# Create fresh train/val folders
for split in ["train", "val"]:
    for cls in CLASS_NAMES:
        (DATA_DIR / split / cls).mkdir(parents=True, exist_ok=True)

print("🗂️ Splitting dataset...")
for cls in CLASS_NAMES:
    images = list((SOURCE_DIR / cls / cls).glob("*.*"))
    images = [i for i in images if i.suffix.lower() in [".jpg", ".jpeg", ".png"]]
    random.shuffle(images)
    split_idx  = int(len(images) * 0.8)
    train_imgs = images[:split_idx]
    val_imgs   = images[split_idx:]
    for img in train_imgs:
        shutil.copy(img, DATA_DIR / "train" / cls / img.name)
    for img in val_imgs:
        shutil.copy(img, DATA_DIR / "val" / cls / img.name)
    print(f"  {cls:22s}: {len(train_imgs)} train | {len(val_imgs)} val")

print("\n✅ Dataset ready! 1000 images per class 🐟")

import os
path = Path("fish_dataset/Fish_Dataset/Fish_Dataset")
print(os.listdir(path))

fig, axes = plt.subplots(3, 3, figsize=(12, 10))
fig.suptitle("Sample Images per Class", fontsize=13, fontweight="bold")
axes = axes.flatten()
for i, cls in enumerate(CLASS_NAMES):
    imgs = [f for f in (DATA_DIR / "train" / cls).glob("*.*")
            if f.suffix.lower() in [".jpg", ".jpeg", ".png"]]
    if imgs:
        try:
            axes[i].imshow(Image.open(imgs[0]).convert("RGB"))
        except:
            pass
    axes[i].set_title(cls, fontweight="bold", fontsize=9)
    axes[i].axis("off")
plt.tight_layout()
plt.show()

BATCH_SIZE = 32
IMG_SIZE   = 224

train_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(15),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

val_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

train_dataset = datasets.ImageFolder(DATA_DIR / "train", transform=train_transform)
val_dataset   = datasets.ImageFolder(DATA_DIR / "val",   transform=val_transform)

train_loader  = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True,  num_workers=2)
val_loader    = DataLoader(val_dataset,   batch_size=BATCH_SIZE, shuffle=False, num_workers=2)

print(f"Train  : {len(train_dataset)} images")
print(f"Val    : {len(val_dataset)} images")
print(f"Classes: {train_dataset.classes}")

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = models.resnet50(pretrained=True)

# Freeze all base layers
for param in model.parameters():
    param.requires_grad = False

# Custom classifier head
num_features = model.fc.in_features
model.fc = nn.Sequential(
    nn.Linear(num_features, 512),
    nn.ReLU(),
    nn.Dropout(0.4),
    nn.Linear(512, 256),
    nn.ReLU(),
    nn.Dropout(0.3),
    nn.Linear(256, len(CLASS_NAMES))
)

model = model.to(DEVICE)

trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"\n🧠 ResNet50 loaded | Trainable params: {trainable:,}")

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.fc.parameters(), lr=0.001, weight_decay=1e-4)
scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=5, gamma=0.5)

EPOCHS = 15

train_losses, val_losses = [], []
train_accs,   val_accs   = [], []
best_val_acc = 0.0

print("\n🚀 Training started...\n")
print(f"{'Epoch':<8}{'Train Loss':<14}{'Train Acc':<14}{'Val Loss':<14}{'Val Acc'}")
print("─" * 58)

for epoch in range(EPOCHS):

    # Train
    model.train()
    t_loss, correct, total = 0.0, 0, 0
    for images, labels in train_loader:
        images, labels = images.to(DEVICE), labels.to(DEVICE)
        optimizer.zero_grad()
        outputs = model(images)
        loss    = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        t_loss  += loss.item()
        _, pred  = outputs.max(1)
        correct += pred.eq(labels).sum().item()
        total   += labels.size(0)

    train_loss = t_loss / len(train_loader)
    train_acc  = 100.0 * correct / total
    train_losses.append(train_loss)
    train_accs.append(train_acc)

    # Validate
    model.eval()
    v_loss, v_correct, v_total = 0.0, 0, 0
    with torch.no_grad():
        for images, labels in val_loader:
            images, labels = images.to(DEVICE), labels.to(DEVICE)
            outputs   = model(images)
            loss      = criterion(outputs, labels)
            v_loss   += loss.item()
            _, pred   = outputs.max(1)
            v_correct += pred.eq(labels).sum().item()
            v_total   += labels.size(0)

    val_loss = v_loss / len(val_loader)
    val_acc  = 100.0 * v_correct / v_total
    val_losses.append(val_loss)
    val_accs.append(val_acc)

    scheduler.step()

    print(f"{epoch+1:<8}{train_loss:<14.4f}{train_acc:<14.2f}{val_loss:<14.4f}{val_acc:.2f}%")

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save({
            'model_state_dict': model.state_dict(),
            'classes'         : train_dataset.classes,
            'val_acc'         : val_acc,
            'epoch'           : epoch + 1
        }, "fish_model.pth")
        print(f"         💾 Saved! Best val acc: {best_val_acc:.2f}%")

print(f"\n✅ Training done! Best Val Accuracy: {best_val_acc:.2f}%")

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("Training Results", fontsize=13, fontweight="bold")

ax1.plot(train_losses, label="Train", color="#2563eb", linewidth=2)
ax1.plot(val_losses,   label="Val",   color="#e53935", linewidth=2)
ax1.set_title("Loss"); ax1.set_xlabel("Epoch"); ax1.legend(); ax1.grid(alpha=0.3)

ax2.plot(train_accs, label="Train", color="#2563eb", linewidth=2)
ax2.plot(val_accs,   label="Val",   color="#e53935", linewidth=2)
ax2.set_title("Accuracy (%)"); ax2.set_xlabel("Epoch"); ax2.legend(); ax2.grid(alpha=0.3)

plt.tight_layout()
plt.savefig("training_curves.png", dpi=150)
plt.show()


# Confusion Matrix & Classification Report


checkpoint = torch.load("fish_model.pth", map_location=DEVICE)
model.load_state_dict(checkpoint['model_state_dict'])
model.eval()

all_preds, all_labels = [], []
with torch.no_grad():
    for images, labels in val_loader:
        images  = images.to(DEVICE)
        outputs = model(images)
        _, pred = outputs.max(1)
        all_preds.extend(pred.cpu().numpy())
        all_labels.extend(labels.numpy())

print(f"\n📊 Final Accuracy: {accuracy_score(all_labels, all_preds)*100:.2f}%")

cm = confusion_matrix(all_labels, all_preds)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES, linewidths=0.5)
plt.xlabel("Predicted"); plt.ylabel("Actual")
plt.title("Confusion Matrix", fontweight="bold")
plt.tight_layout()
plt.savefig("confusion_matrix.png", dpi=150)
plt.show()

print("\n📋 Classification Report:")
print(classification_report(all_labels, all_preds, target_names=CLASS_NAMES))

from google.colab import files
files.download("fish_model.pth")